# Site
repository: oguzhaniksat/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Oguzhan Taskin
title: Master's Degree in Marketing Analytics
email: oguzhaniksat@gmail.com
website: www.github.com/oguzhaniksat/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  www.github.com/oguzhaniksat
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/oguzhan-taskin/
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Recent master graduate who has data analytics skills with Marketing and Business perspective. Obtained problem solving, presentation and critical thinking skills throughout education and professional experience.Experience in <mark>R</mark> and enthusiastic about working with data

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KOCTAS (KOC Inc. / B&Q Inc. JOINT VENTURE)
        # link_text: boringcompany.com
        sub_title: Intern, SEO and Category Intern at E-Commerce
        caption: March 2019 - August 2019
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           Reporting market price of the newly-obtained products and potential promotion opportunities.
           Converting supplier’s description about products to KOCTAS’s webpage.
           Forecasting sales performance of categories in both Excel and SAP.
           Helped to Analytics team to improve web-traƧc via Google Analytics.
           
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tilburg University
        caption: 2020 - 2021
        sub_title: MSc Marketing Analytics
        description: | # this will include new lines to allow paragraphs
         Thesis Title: Understanding the eƦects of promotions on playlists’ followers and listeners on Spotify
    content:
      - layout: left
        title: Ozyegin University
        caption: 2013 - 2019
        sub_title: BSc Marketing Analytics
        description: | # this will include new lines to allow paragraphs
         Honors: 50% Performance Scholarship + %25 Hayatının Oyunu (Game of Your Life) Contest
         
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
